# Generated by Django 3.1.3 on 2020-11-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200930_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='architecture',
            field=models.CharField(blank=True, choices=[(None, '---'), ('x86', 'x86'), ('x64', 'x64'), ('arm', 'arm')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='family',
            field=models.CharField(blank=True, choices=[(None, '---'), ('Debian', 'Debian'), ('Ubuntu', 'Ubuntu'), ('Fedora', 'Fedora')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='kernel',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='operating_system',
            field=models.CharField(choices=[(None, '---'), ('Linux', 'Linux'), ('Windows', 'Windows'), ('Mac', 'Mac'), ('Other', 'Other')], default='Linux', max_length=10),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='operating_system',
            field=models.CharField(choices=[(None, '---'), ('Linux', 'Linux'), ('Windows', 'Windows'), ('Mac', 'Mac'), ('Other', 'Other')], default='Linux', max_length=10),
        ),
    ]
