# Generated by Django 3.1.3 on 2020-11-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20201103_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump',
            name='architecture',
            field=models.CharField(blank=True, choices=[(None, '---'), ('x86', 'x86'), ('x64', 'x64'), ('arm', 'arm'), ('amd64', 'amd64')], max_length=10, null=True),
        ),
    ]
